reporting-disabled = false

hostname = "localhost"

[meta]
  dir = "/data/meta"

[data]
  dir = "/data/db"
  wal-dir = "/data/wal"


[admin]
  enabled = true
  bind-address = ":8083"
  https-enabled = false

[http]
  enabled = true
  bind-address = ":8086"
  auth-enabled = true
  log-enabled = true
  https-enabled = false

[continuous_queries]
  log-enabled = true
  enabled = true
